# Generated by Django 2.2.12 on 2020-04-27 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='autor',
        ),
        migrations.AddField(
            model_name='ebook',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Autor'),
            preserve_default=False,
        ),
    ]
