# Generated by Django 2.2.12 on 2020-05-04 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200427_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
