# Generated by Django 2.2.12 on 2020-05-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
