# Generated by Django 2.2.12 on 2020-05-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products_moved',
            field=models.BooleanField(default=False),
        ),
    ]
